# GR1 Robot Joint Configuration used in the action joint space
# Maps joint names to joint indices for easy reference
joints:
  # arm joints
  "left_shoulder_pitch_joint": 0
  "right_shoulder_pitch_joint": 1
  "left_shoulder_roll_joint": 2
  "right_shoulder_roll_joint": 3
  "left_shoulder_yaw_joint": 4
  "right_shoulder_yaw_joint": 5
  "left_elbow_pitch_joint": 6
  "right_elbow_pitch_joint": 7
  "left_wrist_yaw_joint": 8
  "right_wrist_yaw_joint": 9
  "left_wrist_roll_joint": 10
  "right_wrist_roll_joint": 11
  "left_wrist_pitch_joint": 12
  "right_wrist_pitch_joint": 13

  # head joints
  "head_yaw_joint": 14

  # hand joints
  "L_index_proximal_joint": 15
  "L_middle_proximal_joint": 16
  "L_pinky_proximal_joint": 17
  "L_ring_proximal_joint": 18
  "L_thumb_proximal_yaw_joint": 19
  "R_index_proximal_joint": 20
  "R_middle_proximal_joint": 21
  "R_pinky_proximal_joint": 22
  "R_ring_proximal_joint": 23
  "R_thumb_proximal_yaw_joint": 24
  "L_index_intermediate_joint": 25
  "L_middle_intermediate_joint": 26
  "L_pinky_intermediate_joint": 27
  "L_ring_intermediate_joint": 28
  "L_thumb_proximal_pitch_joint": 29
  "R_index_intermediate_joint": 30
  "R_middle_intermediate_joint": 31
  "R_pinky_intermediate_joint": 32
  "R_ring_intermediate_joint": 33
  "R_thumb_proximal_pitch_joint": 34
  "L_thumb_distal_joint": 35
  "R_thumb_distal_joint": 36

# Additional metadata
total_joints: 37
